[project]
name = "shadems"
version = "0.5.5"
description = "Rapid Measurement Set plotting with dask-ms and datashader"
authors = [
    { name = "Ian Heywood", email = "ian.heywood@physics.ox.ac.uk" },
    { name = "RATT" }
]
readme = "README.md"
license = "GPL-2.0-only"
requires-python = ">=3.10,<3.13"
keywords = ["Astronomy", "Visualisation", "Packaging"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Astronomy"
]
dependencies = [
    "bokeh>=3.8.2,<4",
    "cmasher>=1.6.3,<2",
    "dask>=2024.1.0,<2025",
    "dask-ms[xarray]>=0.2.20,<0.3; python_version < '3.12'",
    "dask-ms[xarray]>=0.2.23,<0.3; python_version >= '3.12'",
    "datashader>=0.16.0,<0.17",
    "fonttools>=4.61.0,<5",
    "future-fstrings>=1.2.0,<2",
    "holoviews>=1.20.0,<2",
    "matplotlib>=3.9.4,<4",
    "pillow>=12.1.1,<13",
    "pyarrow>=24.0.0",
    "requests>=2.32.4,<3",
    "tornado>=6.5.1,<7",
    "urllib3>=2.6.3,<3"
]

[project.optional-dependencies]
testing = ["pytest>=7.2.2,<8", "pytest-flake8>=1.1.1,<2"]

[project.urls]
Homepage = "https://github.com/ratt-ru/shadeMS"
Repository = "https://github.com/ratt-ru/shadeMS"

[project.scripts]
shadems = "shade_ms.main:driver"

[dependency-groups]
tests = [
    "pytest>=7.2.2,<8",
    "pytest-flake8>=1.1.1,<2"
]

[tool.uv]
default-groups = ["tests"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::FutureWarning:dask.dataframe",
    "ignore:Increasing number of chunks by factor of .*:dask.array.PerformanceWarning"
]

[tool.hatch.build.targets.wheel]
packages = ["shade_ms"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
