name: Ubuntu CI

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
  schedule:
    - cron: '30 2 * * 1,4' # Every Monday and Thursday @ 2h30am UTC


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync project dependencies
        run: uv sync --group tests

      - name: Check installed version command
        run: uv run shadems --version

      - name: Test command
        run: uv run shadems --help

      - name: Run testsuite
        run: uv run pytest -v

      - name: Download test dataset
        run: curl https://ratt-public-data.s3.af-south-1.amazonaws.com/test-data/HLTau_B6cont.calavg.tav300s.tar.xz | tar xJf -

      - name: Run end to end test
        run: uv run shadems HLTau_B6cont.calavg.tav300s

      - name: Run end to end test with discrete colour axis
        run: uv run shadems -x TIME -y uv -c FLAG HLTau_B6cont.calavg.tav300s

      - name: Run end to end test with averaging
        run: uv run shadems --average CHAN:4 --average TIME:60 HLTau_B6cont.calavg.tav300s


  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   # Run on a push to a tag or master
  #   if: >
  #     github.event_name == 'push' &&
  #     (startsWith(github.event.ref, 'refs/tags') ||
  #      github.event.ref == 'refs/heads/master')

  #   steps:
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.8

  #     - name: Install latest setuptools, wheel, pip
  #       run: python3 -m pip install -U pip setuptools wheel

  #     - name: Install dephell
  #       run: curl -L dephell.org/install | python3

  #     - name: Checkout source
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - name: Build distributions
  #       run: python setup.py sdist bdist_wheel

  #     - name: Publish distribution 📦 to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@master
  #       with:
  #         user: __token__
  #         password: ${{ secrets.test_pypi_token }}
  #         repository_url: https://test.pypi.org/legacy/
  #       continue-on-error: true

  #     - name: Publish distribution 📦 to PyPI
  #       uses: pypa/gh-action-pypi-publish@master
  #       if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
  #       with:
  #         user: __token__
  #         password: ${{ secrets.pypi_token }}
