name: Upload Python Package

on:
  release:
    types: [published]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Build distribution
      run: uv build

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
